version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 9090:27017
    volumes:
      - mongodb_data:/data/db

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=vidhu369
      - MYSQL_DATABASE=capstone
    volumes:
      - mysql_data:/mysql_data/db

  app:
    build: .
#      context: .
#      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - mysql
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://localhost:27017/Capstone-backend
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/capstone
      - SPRING_DATASOURCE_USERNAME=vidhyasakar
      - SPRING_DATASOURCE_PASSWORD=vidhu369

volumes:
  mongodb_data:
  mysql_data:


#version: "3"
#services:
#  app:
#    image: capstone:latest
#    ports:
#      - 8083:9090
#    working_dir: /app
#    volumes:
#      - ./:/app
#    environment:
#      MYSQL_HOST: localhost
#      MYSQL_USER: vidhyasakar
#      MYSQL_PASSWORD: vidhu369
#      MYSQL_DB: capstone
#  mysql:
#    image: mysql:latest
#    volumes:
#      - mysql-data:/usr/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: vidhu369
#      MYSQL_DATABASE: capstone
#
#  mongodb:
#    image: mongo:latest
##    ports:
##      - 27017:8082
##    network_mode: host
#    volumes:
#      - mongo_database:/data/capstone
#    networks:
#      - capstone-nd-mongo
#
#  capstone:
#    image: capstone:latest
#    build: .
#    depends_on:
#      - mongodb
#    ports:
#      - 8084:8084
#    networks:
#      - capstone-nd-mongo
#
#networks:
#  capstone-nd-mongo:
#volumes:
#  mongo_database:
#  mysql-data: